### ISSUE TITLE
Add barometer

### ISSUE THREAD

**Issue by wiktorwieclaw** [grupacosmo/cansat#18]
We'd like to use the air pressure to calculate altitute. We will use a BMP280 module, there is a nice crate for it called [bme280](https://crates.io/crates/bme280)

**Comment by wiktorwieclaw** [comment]
There is a embedded-hal version conflict between [bmp280](https://crates.io/crates/bme280) and [stm32f4xx-hal](https://crates.io/crates/stm32f4xx-hal). Use [our fork](https://github.com/grupacosmo/bme280-rs) instead like so:
```toml
[dependencies]
bme280 = { git = "https://github.com/grupacosmo/bme280-rs", default-features = false, features = ["defmt"] }
```
